### Create a new user
POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "user@example.com",
    "password": "string"
}


### Sign in user
POST http://localhost:3000/auth/signin
content-type: application/json

{
    "email": "user@example.com",
    "password": "string"
}

### Get a user by ID
GET http://localhost:3000/auth/2


### Get current user 
GET http://localhost:3000/auth/me



### Logout current user 
POST http://localhost:3000/auth/signout

















### Get a users by their email
GET http://localhost:3000/auth?email=user@example.com

### Update a user with an ID
PATCH http://localhost:3000/auth/1
content-type: application/json

{
    "password": "string"
}

### Delete a user with an ID
DELETE http://localhost:3000/auth/1


